language: node_js

cache:
  npm: false
  directories:
    - '~/.pnpm-store'

before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
  - pnpm config set store-dir ~/.pnpm-store
  - pnpm danger ci

install:
  - pnpm install

deploy:
  skip_cleanup: true
